In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.tree import DecisionTreeClassifier

In [44]:
X, y = make_moons(n_samples=1000, noise=0.4)

In [45]:
ssplit = ShuffleSplit(n_splits=1000, train_size=0.8, test_size=0.2, random_state=42)

In [59]:
trees = []

for train_dex, test_dex in ssplit.split(X):
    dec_tree = DecisionTreeClassifier(max_leaf_nodes=5)
    dec_tree.fit(X[train_dex], y[train_dex])
    trees.append(dec_tree)
    print(cross_val_score(dec_tree, X[train_dex], y[train_dex], cv=3, scoring="accuracy"))

[0.86891386 0.84644195 0.87218045]
[0.87265918 0.84644195 0.88721805]
[0.87265918 0.83146067 0.83834586]
[0.86142322 0.81273408 0.82706767]
[0.85018727 0.82771536 0.86090226]
[0.86142322 0.82397004 0.84586466]
[0.83520599 0.86142322 0.85714286]
[0.86891386 0.83146067 0.82706767]
[0.82022472 0.85018727 0.84962406]
[0.84269663 0.85018727 0.84962406]
[0.86516854 0.8164794  0.82330827]
[0.82397004 0.88014981 0.82706767]
[0.86516854 0.82397004 0.83834586]
[0.87265918 0.85393258 0.81578947]
[0.86516854 0.84644195 0.83458647]
[0.86516854 0.84644195 0.84962406]
[0.84644195 0.83520599 0.84962406]
[0.83520599 0.88389513 0.85338346]
[0.88389513 0.85018727 0.85338346]
[0.86142322 0.85393258 0.86466165]
[0.83895131 0.86891386 0.85338346]
[0.83520599 0.83146067 0.85338346]
[0.84644195 0.83520599 0.84962406]
[0.86142322 0.87265918 0.84586466]
[0.82397004 0.8576779  0.84210526]
[0.87265918 0.83146067 0.87218045]
[0.84269663 0.85018727 0.87969925]
[0.8576779  0.86516854 0.84962406]
[0.85018727 0.876404

[0.84644195 0.83895131 0.87218045]
[0.87640449 0.87265918 0.83082707]
[0.83895131 0.88014981 0.86842105]
[0.83895131 0.84269663 0.86466165]
[0.8576779  0.88389513 0.84210526]
[0.88389513 0.82771536 0.84586466]
[0.86891386 0.84269663 0.83082707]
[0.85393258 0.86891386 0.84962406]
[0.85018727 0.85018727 0.85338346]
[0.82397004 0.82771536 0.87218045]
[0.83895131 0.82771536 0.86090226]
[0.86891386 0.8576779  0.86090226]
[0.82397004 0.8164794  0.88345865]
[0.8576779  0.8576779  0.85714286]
[0.8164794  0.84269663 0.86842105]
[0.82397004 0.88389513 0.83834586]
[0.84269663 0.86142322 0.83082707]
[0.87640449 0.82397004 0.83834586]
[0.83520599 0.84644195 0.86090226]
[0.86142322 0.86891386 0.84586466]
[0.85018727 0.8576779  0.85714286]
[0.84269663 0.88389513 0.83834586]
[0.85393258 0.86516854 0.85338346]
[0.82397004 0.89138577 0.83834586]
[0.84644195 0.82771536 0.85714286]
[0.84269663 0.8164794  0.86842105]
[0.83146067 0.87640449 0.85714286]
[0.84644195 0.85393258 0.82330827]
[0.83146067 0.835205

[0.8576779  0.86142322 0.85714286]
[0.8576779  0.84269663 0.85338346]
[0.8576779  0.8576779  0.84586466]
[0.87265918 0.82022472 0.87218045]
[0.85393258 0.85018727 0.85714286]
[0.80898876 0.80524345 0.86466165]
[0.8576779  0.86516854 0.84210526]
[0.82771536 0.82771536 0.84210526]
[0.83895131 0.86516854 0.86842105]
[0.8576779  0.82397004 0.82706767]
[0.8576779  0.85393258 0.87218045]
[0.86516854 0.88389513 0.84210526]
[0.85393258 0.80524345 0.83834586]
[0.85018727 0.86142322 0.83834586]
[0.87265918 0.86142322 0.87969925]
[0.81273408 0.83520599 0.81578947]
[0.85393258 0.83520599 0.86842105]
[0.87265918 0.86891386 0.86842105]
[0.85393258 0.84269663 0.84586466]
[0.8576779  0.85393258 0.84962406]
[0.83146067 0.85018727 0.83458647]
[0.86516854 0.84269663 0.86466165]
[0.82397004 0.86516854 0.84586466]
[0.86142322 0.85393258 0.86090226]
[0.80898876 0.83895131 0.86842105]
[0.80524345 0.87265918 0.87593985]
[0.85393258 0.83520599 0.84962406]
[0.87265918 0.84269663 0.82706767]
[0.85393258 0.850187

[0.84644195 0.82397004 0.86842105]
[0.86142322 0.88014981 0.85714286]
[0.86142322 0.82771536 0.86842105]
[0.85018727 0.83146067 0.86842105]
[0.86516854 0.8164794  0.85714286]
[0.85018727 0.85393258 0.86090226]
[0.85393258 0.8576779  0.83834586]
[0.84269663 0.85393258 0.81954887]
[0.82771536 0.83895131 0.87593985]
[0.83146067 0.87265918 0.84962406]
[0.8576779  0.84644195 0.86090226]
[0.85018727 0.82022472 0.84210526]
[0.84644195 0.84644195 0.86842105]
[0.87265918 0.87640449 0.83834586]
[0.86142322 0.86891386 0.87218045]
[0.86516854 0.84644195 0.82330827]
[0.85018727 0.83146067 0.85338346]
[0.83895131 0.8576779  0.83834586]
[0.86142322 0.87265918 0.79699248]
[0.86142322 0.86516854 0.83458647]
[0.86142322 0.86142322 0.81203008]
[0.84269663 0.86516854 0.83082707]
[0.8576779  0.88389513 0.85714286]
[0.81273408 0.8576779  0.87218045]
[0.85018727 0.83520599 0.86090226]
[0.83146067 0.85018727 0.88345865]
[0.83895131 0.83146067 0.86090226]
[0.82771536 0.90262172 0.82706767]
[0.78277154 0.838951

[0.87265918 0.83895131 0.84962406]
[0.85018727 0.82397004 0.88345865]
[0.85018727 0.88014981 0.82330827]
[0.86142322 0.8164794  0.87593985]
[0.8164794  0.86516854 0.85714286]
[0.84644195 0.86142322 0.83458647]
[0.84644195 0.86142322 0.87218045]
[0.83146067 0.84644195 0.88721805]
[0.8576779  0.8164794  0.83082707]
[0.8576779  0.86891386 0.85714286]
[0.8576779  0.82397004 0.86466165]
[0.8576779  0.86142322 0.86466165]
[0.82771536 0.8576779  0.86842105]
[0.86516854 0.83895131 0.85338346]
[0.83146067 0.85018727 0.84210526]
[0.82397004 0.86891386 0.85714286]
[0.82397004 0.86516854 0.84962406]
[0.84644195 0.85393258 0.89097744]
[0.85018727 0.83895131 0.86466165]
[0.83895131 0.87265918 0.86842105]
[0.82771536 0.87265918 0.83458647]
[0.87640449 0.83895131 0.83834586]
[0.83895131 0.86142322 0.83834586]
[0.83520599 0.83895131 0.84586466]
[0.8576779  0.88014981 0.84962406]
[0.8576779  0.8576779  0.84210526]
[0.82771536 0.85393258 0.83834586]
[0.84644195 0.84269663 0.83834586]
[0.86142322 0.831460

In [72]:
def predict(X):
    for tree in trees:
        tree.predict(X)
    

1
0


In [58]:
trees

[]