In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [3]:
X, y = make_moons(n_samples=1000, noise=0.4)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [44]:
dec_tree = DecisionTreeClassifier()

In [45]:
parameters = [
    {"min_samples_leaf": [2, 3, 5, 7]},
    {"max_leaf_nodes": [2 ,5, 7 ,10, 15]},
    {"min_samples_leaf": [2, 3, 5]},
    {"max_leaf_nodes": [None, 10, 15]},
    
]

gridcv = GridSearchCV(dec_tree, parameters, cv=3)

In [46]:
gridcv.fit(X_train, y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid=[{'min_samples_leaf': [2, 3, 5, 7]},
                 

In [47]:
gridcv.best_params_

{'max_leaf_nodes': 5}

In [48]:
dec_tree_tuned = DecisionTreeClassifier(max_leaf_nodes=5)

In [49]:
dec_tree_tuned.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=5,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [50]:
y_train_preds = cross_val_score(dec_tree_tuned, X_train, y_train, cv=3, scoring="accuracy")

In [51]:
y_train_preds

array([0.8576779 , 0.85393258, 0.86842105])

In [52]:
y_train_preds.mean()

0.8600105131743216

In [53]:
dec_tree_tuned.predict(X_test)

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1], dtype=int64)

In [54]:
confusion_matrix(dec_tree_tuned.predict(X_test), y_test)

array([[96, 12],
       [10, 82]], dtype=int64)

In [55]:
cross_val_score(dec_tree_tuned, X_test, y_test, cv=3, scoring="accuracy")

array([0.89552239, 0.89552239, 0.86363636])